from enum import Enum


class AttackFamily(str, Enum):
    AUTHORITY_IMPERSONATION = "AUTHORITY_IMPERSONATION"
    TOOL_WORKFLOW_BYPASS = "TOOL_WORKFLOW_BYPASS"
    MULTI_TURN_MANIPULATION = "MULTI_TURN_MANIPULATION"
    INDIRECT_PROMPT_INJECTION = "INDIRECT_PROMPT_INJECTION"

    # Stretch goals
    CONTEXT_CONFLICT = "CONTEXT_CONFLICT"
    DATA_ACCESS_BOUNDARY = "DATA_ACCESS_BOUNDARY"