"""Add Day 3 Finding and Regression models

Revision ID: 3b6e7e98f07d
Revises: 98c456a9f7df
Create Date: 2026-09-14 21:01:13.035186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b6e7e98f07d'
down_revision: Union[str, Sequence[str], None] = '98c456a9f7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regression_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('build', sa.String(length=50), nullable=False),
    sa.Column('attack_run_id', sa.String(length=36), nullable=False),
    sa.Column('old_label', sa.String(length=50), nullable=False),
    sa.Column('new_label', sa.String(length=50), nullable=False),
    sa.Column('status_diff', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attack_run_id'], ['attack_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regression_alerts_attack_run_id'), 'regression_alerts', ['attack_run_id'], unique=False)
    op.drop_table('regression_results')
    op.drop_table('regression_tests')
    op.add_column('findings', sa.Column('case_id', sa.String(length=50), nullable=False))
    op.add_column('findings', sa.Column('build', sa.String(length=50), nullable=False))
    op.add_column('findings', sa.Column('evaluation_type', sa.String(length=50), nullable=False))
    op.add_column('findings', sa.Column('n_runs', sa.Integer(), nullable=False))
    op.add_column('findings', sa.Column('verdicts', sa.JSON(), nullable=False))
    op.add_column('findings', sa.Column('verdict_counts', sa.JSON(), nullable=False))
    op.add_column('findings', sa.Column('unanimous', sa.Boolean(), nullable=False))
    op.add_column('findings', sa.Column('has_majority', sa.Boolean(), nullable=False))
    op.add_column('findings', sa.Column('majority_verdict', sa.String(length=50), nullable=False))
    op.add_column('findings', sa.Column('worst_observed', sa.String(length=50), nullable=False))
    op.add_column('findings', sa.Column('judge_votes_per_verdict', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('judge_provider', sa.String(length=50), nullable=True))
    op.add_column('findings', sa.Column('judge_model', sa.String(length=100), nullable=True))
    op.add_column('findings', sa.Column('prompt_version', sa.String(length=50), nullable=True))
    op.add_column('findings', sa.Column('trace_refs', sa.JSON(), nullable=False))
    op.drop_column('findings', 'rationale')
    op.drop_column('findings', 'label')
    op.drop_column('findings', 'confidence')
    op.drop_column('findings', 'evidence_event_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('evidence_event_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('findings', sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('findings', 'trace_refs')
    op.drop_column('findings', 'prompt_version')
    op.drop_column('findings', 'judge_model')
    op.drop_column('findings', 'judge_provider')
    op.drop_column('findings', 'judge_votes_per_verdict')
    op.drop_column('findings', 'worst_observed')
    op.drop_column('findings', 'majority_verdict')
    op.drop_column('findings', 'has_majority')
    op.drop_column('findings', 'unanimous')
    op.drop_column('findings', 'verdict_counts')
    op.drop_column('findings', 'verdicts')
    op.drop_column('findings', 'n_runs')
    op.drop_column('findings', 'evaluation_type')
    op.drop_column('findings', 'build')
    op.drop_column('findings', 'case_id')
    op.create_table('regression_tests',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('attack_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('baseline_run_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], name=op.f('regression_tests_attack_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['attack_runs.id'], name=op.f('regression_tests_baseline_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('regression_tests_pkey'))
    )
    op.create_table('regression_results',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('regression_test_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('new_run_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('old_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('new_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status_diff', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['new_run_id'], ['attack_runs.id'], name=op.f('regression_results_new_run_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regression_test_id'], ['regression_tests.id'], name=op.f('regression_results_regression_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('regression_results_pkey'))
    )
    op.drop_index(op.f('ix_regression_alerts_attack_run_id'), table_name='regression_alerts')
    op.drop_table('regression_alerts')
    # ### end Alembic commands ###
