"""Initial schema

Revision ID: 98c456a9f7df
Revises: 
Create Date: 2026-08-28 17:57:39.535803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c456a9f7df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    op.create_table('agent_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('protected_tools', sa.JSON(), nullable=False),
    sa.Column('tool_config', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraints',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('protected_action', sa.String(length=100), nullable=True),
    sa.Column('required_condition', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('evaluation_type', sa.String(length=20), nullable=False),
    sa.Column('mvp_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attacks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('constraint_id', sa.String(length=50), nullable=True),
    sa.Column('target_policy', sa.String(length=50), nullable=False),
    sa.Column('target_constraint', sa.Text(), nullable=True),
    sa.Column('attack_family', sa.String(length=50), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('prompt', sa.JSON(), nullable=False),
    sa.Column('expected_label', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['constraint_id'], ['constraints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attack_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attack_id', sa.String(length=100), nullable=False),
    sa.Column('agent_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('deterministic_label', sa.String(length=50), nullable=True),
    sa.Column('evaluation_label', sa.String(length=50), nullable=True),
    sa.Column('initial_state', sa.JSON(), nullable=True),
    sa.Column('deterministic_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attack_run_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_event_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attack_run_id'], ['attack_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_attack_run_id'), 'findings', ['attack_run_id'], unique=False)
    op.create_table('regression_tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attack_id', sa.String(length=100), nullable=False),
    sa.Column('baseline_run_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['attack_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attack_run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool', sa.String(length=100), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('state_before', sa.JSON(), nullable=True),
    sa.Column('state_after', sa.JSON(), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['attack_run_id'], ['attack_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_events_attack_run_id'), 'trace_events', ['attack_run_id'], unique=False)
    op.create_table('regression_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('regression_test_id', sa.String(length=36), nullable=False),
    sa.Column('new_run_id', sa.String(length=36), nullable=False),
    sa.Column('old_label', sa.String(length=50), nullable=False),
    sa.Column('new_label', sa.String(length=50), nullable=False),
    sa.Column('status_diff', sa.String(length=30), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['new_run_id'], ['attack_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regression_test_id'], ['regression_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regression_results')
    op.drop_index(op.f('ix_trace_events_attack_run_id'), table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_table('regression_tests')
    op.drop_index(op.f('ix_findings_attack_run_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('attack_runs')
    op.drop_table('attacks')
    op.drop_table('constraints')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_table('tools')
    op.drop_table('agents')
    # ### end Alembic commands ###
